### ISSUE TITLE
Introduction about bitcoin is too long, it's already described in detail in other books

### ISSUE THREAD

**Issue by jasonzhouu** [renepickhardt/The-Lightning-Network-Book#21]
It should concentrate in lightning network, this is the reason why others read this book with title "The lightning network book".

**Comment by renepickhardt** [comment]
Thanks for the feedback on a content level. This is highly appriciated

Not sure where and how to shorten it though. Let me elaborate why:  From the talks I give I see how often basics about Bitcoin transactions are misunderstood. Those basics are needed with lightning as it plays with Bitcoin transactions quite a lot. My idea was to include this to make the book somewhat independent on other books. If readers already know it they can skip if not they might be happy to learn the parts that are relevant for lightning at one spot. Does that reasoning make sense? Would love to hear more opinions (:

**Comment by jasonzhouu** [comment]
I get it. It'a just a choice to be independent or concentrate.
