### ISSUE TITLE
Adding a list of essential resources to the appendix

### ISSUE THREAD

**Issue by 8go** [renepickhardt/The-Lightning-Network-Book#24]
Hello Rene,

I would like to contribute. I added some content to the https://lightningwiki.net wiki. I also already added your effort to create this book there in order to give it a shout-out. 

As first step to help with this book I might offer to write an initial draft of a "Resource List" chapter for the appendix. 

Would that be helpful? If you give the OK, I  could start with that. 

Awaiting your response ...

**Comment by renepickhardt** [comment]
I like the idea of such a list. I would however add them while writing the book and using them instead of adding a general list of resoruces. What did you have in mind?

**Comment by 8go** [comment]
I think it would add value to the book. As a reader I would want to know what else is "out there" and also use this list to discover where one can get more details. Specifically a list for those who want to get into setting something up or installing an app or using a service. So, it should at least have the following items:
- for techies: resources for setting up node, resources for participating (code, wikis, marketing, maybe even a list of top github projects, ...), cheatsheets, etc.
- for observers: newsletters, mailing lists, chat channels, reddits, podcast channels, YouTube channels, etc.
- for first users: resources for wallets, wallet reviews, 
- for spenders: where to spend, shops, services accepting Lightning, meta-lists, etc.

Clearly this is not a "write section once and done", as you said as you go through the book you will enhance the list, also I feel that during the time of writing this book many new "resources" will evolve. It is a very dynamic field with new projects starting all the time. 

The ideas was more or less to get a skeleton chapter, an outline, done and then improve it over time.

**Comment by 8go** [comment]
Closed. Too old. See also https://github.com/lnbook/lnbook
